# Site information
Heater.numSites = 22

# Stefan number and saturation temperature
Parfile.mph_Stefan = 0.6376
Parfile.mph_Tsat = 0.1667

# Restart, checkpoint, and plotting options
Parfile.nend = 10000000
Parfile.tmax = 200.0
Parfile.restart = ".false."
Parfile.checkpointFileNumber = 0
Parfile.checkpointFileIntervalTime = 5.0
Parfile.plotFileNumber = 0
Parfile.plotFileIntervalTime = 0.1
