# 1/Fr**2, Fr (Froude Number)
Parfile.ins_gravY = -0.05

# Restart, checkpoint, and plotting options
Parfile.nend = 10000000
Parfile.tmax = 400.0
Parfile.restart = ".true."
Parfile.checkpointFileNumber = 57
Parfile.checkpointFileIntervalTime = 5.0
Parfile.plotFileNumber = 285
Parfile.plotFileIntervalTime = 1.0
