# AMR parameters
Parfile.nblockx = 3  # 18  # 24 #12 #6  #3
Parfile.nblocky = 6  # 36  # 48 #24 #12 #6
Parfile.nblockz = 3  # 18  # 24 #12 #6  #3
Parfile.nrefs = 10

# Time stepping parameters
Parfile.ins_cflFlg = 0
Parfile.ins_cfl = 0.05
Parfile.ins_sigma = 0.05
Parfile.ins_dtSpec = 1.0e-4  # 0.025e-4  # 0.015625e-4 #1.0e-4
Parfile.dtinit = 1.0e-4  # 0.025e-4  # 0.015625e-4 #1.0e-4
Parfile.dtmax = 1.0e-4  # 0.025e-4  # 0.015625e-4 #1.0e-4
