# Number of nucleation sites
Heater.numSites = 90

# Stefan number
Parfile.mph_Stefan = 1.2221

# Restart, checkpoint, and plotting options
Parfile.nend = 10000000
Parfile.tmax = 200.0
Parfile.restart = ".true."
Parfile.checkpointFileNumber = 20
Parfile.checkpointFileIntervalTime = 5.0
Parfile.plotFileNumber = 100
Parfile.plotFileIntervalTime = 1.0
